### ISSUE TITLE
Chown et chmod impossible dans les logs

### ISSUE THREAD

**Issue by Rathorian** [xataz/docker-rtorrent-flood#1]
Salut Xataz,

Je viens d'installer ton image sur mon serveur et dans les logs avec la commande : 

``docker logs rtorrent``

J'ai des chown et chmod qui ne fonctionne pas sur /etc/s6.d car les fichiers et dossiers n'existe pas : 

```
Create torrent user ...
Create folder ...
Generate configuration ...
Apply permissions ...
chown: /etc/s6.d: No such file or directory
chmod: /etc/s6.d/.s6-svscan/finish: No such file or directory
chmod: /etc/s6.d/flood/run: No such file or directory
chmod: /etc/s6.d/rtorrent/run: No such file or directory
2018-02-13 09:52:42,266 INFO supervisord started with pid 26
2018-02-13 09:52:43,269 INFO spawned: 'rtorrent' with pid 29
2018-02-13 09:52:43,272 INFO spawned: 'flood' with pid 30
2018-02-13 09:52:45,134 INFO success: rtorrent entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2018-02-13 09:52:45,134 INFO success: flood entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
```

Est-ce normal ?

Merci

**Comment by xataz** [comment]
Salut,

Nop c'est pas normal, enfin c'est un oublie de ma part, j'ai récemment remplacé s6.d par supervisord (problème d'allocation de term qui faisait utiliser le CPU à fond).

J'ai zappé de supprimer le chown et chmod sur ses répertoires qui n'existe plus.

Je corrige se soir, enfin rien de bloquant en soit.

Merci pour l'issue

**Comment by Rathorian** [comment]
Je viens de vérifier tout ça après avoir posté l'issue.
Effectivement, je vois que tu as changé s6.d par supervisord.

Comme tu dis juste un petit oubli :)

Merci à toi
